import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

abstract class AppLocalizations {
  AppLocalizations(String locale) : localeName = locale;

  final String localeName;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? _AppLocalizationsEn();
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('te'),
    Locale('hi'),
    Locale('ta'),
  ];

  String get appName;
  String get appSubtitle;
  String get clinicalSuite;

  String get login;
  String get register;
  String get email;
  String get password;
  String get confirmPassword;
  String get forgotPassword;
  String get signIn;
  String get signUp;
  String get logout;
  String get fullName;
  String get role;
  String get doctorDemo;
  String get adminDemo;
  String get ophthalmologistRole;
  String get technicianRole;
  String get adminRole;

  String get dashboard;
  String get totalPatients;
  String get totalOCTScans;
  String get analysesCompleted;
  String get analysesPending;
  String get reportsGenerated;
  String get recentAnalyses;
  String get quickActions;
  String get welcomeText;
  String get activeSession;
  String get newScan;
  String get viewAllHistory;

  String get patients;
  String get addPatient;
  String get patientDetails;
  String get patientId;
  String get name;
  String get age;
  String get gender;
  String get contact;
  String get dateRegistered;
  String get scanHistory;
  String get allGenders;
  String get female;
  String get male;
  String get other;
  String get eyeCondition;
  String get medicalHistory;
  String get savePatientRecord;

  String get uploadOCT;
  String get selectImage;
  String get chooseFile;
  String get upload;
  String get remove;
  String get replace;
  String get validateImage;
  String get startAnalysis;
  String get acquisitionParameters;
  String get eyeLaterality;
  String get rightEye;
  String get leftEye;
  String get acquisitionDevice;
  String get axialCalibration;
  String get dropzonePrompt;
  String get supportedFormats;
  String get sampleScans;
  String get validOCTDetected;
  String get invalidOCTDetected;
  String get startSegmentationBtn;

  String get analysis;
  String get preprocessing;
  String get enhancedPreprocessing;
  String get segmentation;
  String get unetModel;
  String get processing;
  String get completed;
  String get failed;
  String get retry;
  String get step1Upload;
  String get step2Validation;
  String get step3CLAHE;
  String get step4UNet;
  String get step5Thickness;
  String get step6Workspace;

  String get original;
  String get preprocessed;
  String get segmentationMask;
  String get overlay;
  String get zoom;
  String get reset;
  String get fullScreen;
  String get layerVisibility;
  String get showAll;
  String get hideAll;
  String get overlayOpacity;
  String get aiConfidence;
  String get imageQuality;
  String get executionTime;
  String get calibrated;
  String get uncalibrated;

  String get layerILM;
  String get layerRNFL;
  String get layerGCL;
  String get layerIPL;
  String get layerINL;
  String get layerOPL;
  String get layerONL;
  String get layerRPE;

  String get layer;
  String get mean;
  String get min;
  String get max;
  String get area;
  String get layerThicknessMetrics;

  String get reports;
  String get generateReport;
  String get preview;
  String get download;
  String get share;
  String get reportGenerated;
  String get printReport;
  String get clinicalFindings;
  String get specialistAttestation;
  String get disclaimerNote;

  String get settings;
  String get profile;
  String get appearance;
  String get language;
  String get theme;
  String get lightTheme;
  String get darkTheme;
  String get systemTheme;
  String get notifications;
  String get privacy;
  String get about;
  String get appVersion;
  String get regulatoryDisclaimer;

  String get validOCTRequired;
  String get patientRequired;
  String get uploadSuccess;
  String get analysisSuccess;
  String get reportGeneratedSuccess;
  String get patientCreatedSuccess;
  String get sessionExpired;
  String get confirmDeletePatient;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(_lookupAppLocalizations(locale));
  }

  @override
  bool isSupported(Locale locale) => <String>['en', 'te', 'hi', 'ta'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

AppLocalizations _lookupAppLocalizations(Locale locale) {
  switch (locale.languageCode) {
    case 'te': return _AppLocalizationsTe();
    case 'hi': return _AppLocalizationsHi();
    case 'ta': return _AppLocalizationsTa();
    case 'en':
    default: return _AppLocalizationsEn();
  }
}

// ENGLISH IMPLEMENTATION
class _AppLocalizationsEn extends AppLocalizations {
  _AppLocalizationsEn() : super('en');
  @override String get appName => "RetinaSeg AI";
  @override String get appSubtitle => "Automated Retinal Layer Segmentation in OCT Images";
  @override String get clinicalSuite => "Ophthalmic Imaging Platform";
  @override String get login => "Login";
  @override String get register => "Register";
  @override String get email => "Email Address";
  @override String get password => "Password";
  @override String get confirmPassword => "Confirm Password";
  @override String get forgotPassword => "Forgot Password";
  @override String get signIn => "Sign In";
  @override String get signUp => "Sign Up";
  @override String get logout => "Logout";
  @override String get fullName => "Full Name & Title";
  @override String get role => "Clinical Role";
  @override String get doctorDemo => "Doctor Account";
  @override String get adminDemo => "Admin Account";
  @override String get ophthalmologistRole => "Ophthalmologist";
  @override String get technicianRole => "Ophthalmic Technician";
  @override String get adminRole => "System Administrator";
  @override String get dashboard => "Dashboard";
  @override String get totalPatients => "Total Patients";
  @override String get totalOCTScans => "Total OCT Scans";
  @override String get analysesCompleted => "Analyses Completed";
  @override String get analysesPending => "Analyses Pending";
  @override String get reportsGenerated => "PDF Reports Generated";
  @override String get recentAnalyses => "Recent Retinal OCT Analyses";
  @override String get quickActions => "Quick Actions";
  @override String get welcomeText => "Welcome";
  @override String get activeSession => "Active Clinical Session";
  @override String get newScan => "New Scan";
  @override String get viewAllHistory => "View All History";
  @override String get patients => "Patients";
  @override String get addPatient => "Register Patient";
  @override String get patientDetails => "Patient Details";
  @override String get patientId => "Patient ID / MRN";
  @override String get name => "Full Name";
  @override String get age => "Age";
  @override String get gender => "Gender";
  @override String get contact => "Contact Phone";
  @override String get dateRegistered => "Date Registered";
  @override String get scanHistory => "Scan History";
  @override String get allGenders => "All Genders";
  @override String get female => "Female";
  @override String get male => "Male";
  @override String get other => "Other";
  @override String get eyeCondition => "Eye Condition / Clinical Indication";
  @override String get medicalHistory => "Medical History";
  @override String get savePatientRecord => "Save Patient Record";
  @override String get uploadOCT => "Upload OCT";
  @override String get selectImage => "Select Retinal OCT B-Scan File";
  @override String get chooseFile => "Browse Local Files";
  @override String get upload => "Upload";
  @override String get remove => "Remove";
  @override String get replace => "Replace";
  @override String get validateImage => "Validating OCT Scan...";
  @override String get startAnalysis => "Start AI Retinal Layer Segmentation";
  @override String get acquisitionParameters => "1. Patient & Scan Parameters";
  @override String get eyeLaterality => "Eye Laterality";
  @override String get rightEye => "OD (Right Eye)";
  @override String get leftEye => "OS (Left Eye)";
  @override String get acquisitionDevice => "OCT Acquisition Device";
  @override String get axialCalibration => "Axial Calibration (μm / px)";
  @override String get dropzonePrompt => "Select or Drop Retinal OCT B-Scan File";
  @override String get supportedFormats => "Supported formats: PNG, JPG, JPEG, TIFF (Max 25MB)";
  @override String get sampleScans => "Or load clinical sample scan:";
  @override String get validOCTDetected => "Valid Retinal OCT B-Scan";
  @override String get invalidOCTDetected => "Invalid Image Detected (Non-OCT)";
  @override String get startSegmentationBtn => "Start Enhanced Preprocessing & U-Net Segmentation";
  @override String get analysis => "AI Analysis";
  @override String get preprocessing => "Preprocessing";
  @override String get enhancedPreprocessing => "Enhanced Preprocessing (CLAHE)";
  @override String get segmentation => "U-Net Multi-Layer Segmentation";
  @override String get unetModel => "U-Net 4-Depth Residual Model";
  @override String get processing => "Processing OCT Scan...";
  @override String get completed => "Completed";
  @override String get failed => "Analysis Failed";
  @override String get retry => "Retry Analysis";
  @override String get step1Upload => "1. OCT Image Upload & Storage";
  @override String get step2Validation => "2. Morphological Tissue Validation";
  @override String get step3CLAHE => "3. Bilateral Filter & CLAHE Enhancement";
  @override String get step4UNet => "4. U-Net Multi-Layer Segmentation";
  @override String get step5Thickness => "5. Quantitative Thickness Extraction";
  @override String get step6Workspace => "6. Rendering Multi-Layer Workspace";
  @override String get original => "Original";
  @override String get preprocessed => "Preprocessed (CLAHE)";
  @override String get segmentationMask => "Segmentation Mask";
  @override String get overlay => "Overlay";
  @override String get zoom => "Zoom";
  @override String get reset => "Reset Zoom";
  @override String get fullScreen => "Fit to Screen";
  @override String get layerVisibility => "Retinal Layer Visibility";
  @override String get showAll => "Show All";
  @override String get hideAll => "Hide All";
  @override String get overlayOpacity => "Overlay Opacity";
  @override String get aiConfidence => "AI Confidence";
  @override String get imageQuality => "Image Quality";
  @override String get executionTime => "Execution Time";
  @override String get calibrated => "Calibrated";
  @override String get uncalibrated => "Physical measurement unavailable — calibration data required.";
  @override String get layerILM => "ILM (Inner Limiting Membrane)";
  @override String get layerRNFL => "RNFL (Retinal Nerve Fiber Layer)";
  @override String get layerGCL => "GCL (Ganglion Cell Layer)";
  @override String get layerIPL => "IPL (Inner Plexiform Layer)";
  @override String get layerINL => "INL (Inner Nuclear Layer)";
  @override String get layerOPL => "OPL (Outer Plexiform Layer)";
  @override String get layerONL => "ONL (Outer Nuclear Layer)";
  @override String get layerRPE => "RPE (Retinal Pigment Epithelium)";
  @override String get layer => "Retinal Layer";
  @override String get mean => "Mean";
  @override String get min => "Min";
  @override String get max => "Max";
  @override String get area => "Area (px²)";
  @override String get layerThicknessMetrics => "Layer Thickness Metrics";
  @override String get reports => "Reports";
  @override String get generateReport => "Generate PDF Report";
  @override String get preview => "Preview Report";
  @override String get download => "Download PDF";
  @override String get share => "Share";
  @override String get reportGenerated => "Digital Clinical Reports";
  @override String get printReport => "Print";
  @override String get clinicalFindings => "Automated Clinical Findings";
  @override String get specialistAttestation => "Specialist Review & Attestation";
  @override String get disclaimerNote => "AI assistance only — results are intended for research and decision-support and do not replace clinical diagnosis.";
  @override String get settings => "Settings";
  @override String get profile => "Clinical Profile";
  @override String get appearance => "Appearance";
  @override String get language => "Language";
  @override String get theme => "Theme Mode";
  @override String get lightTheme => "Light";
  @override String get darkTheme => "Dark";
  @override String get systemTheme => "System Default";
  @override String get notifications => "Notifications";
  @override String get privacy => "Privacy & Security";
  @override String get about => "About System";
  @override String get appVersion => "App Version";
  @override String get regulatoryDisclaimer => "Regulatory & Diagnostic Disclaimer";
  @override String get validOCTRequired => "Please upload a valid retinal OCT image.";
  @override String get patientRequired => "Please select a patient record first.";
  @override String get uploadSuccess => "Upload successful";
  @override String get analysisSuccess => "Retinal layer segmentation completed successfully.";
  @override String get reportGeneratedSuccess => "Clinical PDF report generated successfully.";
  @override String get patientCreatedSuccess => "Patient record registered successfully.";
  @override String get sessionExpired => "Session expired. Please sign in again.";
  @override String get confirmDeletePatient => "Are you sure you want to delete this patient record?";
}

// TELUGU IMPLEMENTATION
class _AppLocalizationsTe extends AppLocalizations {
  _AppLocalizationsTe() : super('te');
  @override String get appName => "RetinaSeg AI";
  @override String get appSubtitle => "OCT చిత్రాలలో ఆటోమేటెడ్ రెటీనా పొరల విభజన";
  @override String get clinicalSuite => "ఆఫ్తాల్మిక్ ఇమేజింగ్ ప్లాట్‌ఫారమ్";
  @override String get login => "లాగిన్";
  @override String get register => "రిజిస్టర్";
  @override String get email => "ఈమెయిల్ చిరునామా";
  @override String get password => "పాస్‌వర్డ్";
  @override String get confirmPassword => "పాస్‌వర్డ్ నిర్ధారించండి";
  @override String get forgotPassword => "పాస్‌వర్డ్ మర్చిపోయారా?";
  @override String get signIn => "సైన్ ఇన్";
  @override String get signUp => "సైన్ అప్";
  @override String get logout => "లాగ్ అవుట్";
  @override String get fullName => "పూర్తి పేరు & హోదా";
  @override String get role => "క్లినికల్ పాత్ర";
  @override String get doctorDemo => "డాక్టర్ ఖాతా";
  @override String get adminDemo => "అడ్మిన్ ఖాతా";
  @override String get ophthalmologistRole => "నేత్ర వైద్య నిపుణుడు";
  @override String get technicianRole => "ఆఫ్తాల్మిక్ టెక్నీషియన్";
  @override String get adminRole => "సిస్టమ్ అడ్మినిస్ట్రేటర్";
  @override String get dashboard => "డాష్‌బోర్డ్";
  @override String get totalPatients => "మొత్తం రోగులు";
  @override String get totalOCTScans => "మొత్తం OCT స్కాన్‌లు";
  @override String get analysesCompleted => "పూర్తయిన విశ్లేషణలు";
  @override String get analysesPending => "పెండింగ్ విశ్లేషణలు";
  @override String get reportsGenerated => "PDF నివేదికలు";
  @override String get recentAnalyses => "ఇటీవలి రెటినల్ OCT విశ్లేషణలు";
  @override String get quickActions => "త్వరిత చర్యలు";
  @override String get welcomeText => "స్వాగతం";
  @override String get activeSession => "యాక్టివ్ క్లినికల్ సెషన్";
  @override String get newScan => "కొత్త స్కాన్";
  @override String get viewAllHistory => "మొత్తం చరిత్రను చూడండి";
  @override String get patients => "రోగులు";
  @override String get addPatient => "రోగిని నమోదు చేయండి";
  @override String get patientDetails => "రోగి వివరాలు";
  @override String get patientId => "రోగి ID / MRN";
  @override String get name => "పూర్తి పేరు";
  @override String get age => "వయస్సు";
  @override String get gender => "లింగం";
  @override String get contact => "సంప్రదింపు నంబర్";
  @override String get dateRegistered => "నమోదైన తేదీ";
  @override String get scanHistory => "స్కాన్ చరిత్ర";
  @override String get allGenders => "అన్ని లింగాలు";
  @override String get female => "స్త్రీ";
  @override String get male => "పురుషుడు";
  @override String get other => "ఇతర";
  @override String get eyeCondition => "కంటి పరిస్థితి / క్లినికల్ సూచన";
  @override String get medicalHistory => "వైద్య చరిత్ర";
  @override String get savePatientRecord => "రోగి రికార్డును భద్రపరచండి";
  @override String get uploadOCT => "OCT అప్‌లోడ్";
  @override String get selectImage => "రెటినల్ OCT B-స్కాన్ ఫైల్‌ను ఎంచుకోండి";
  @override String get chooseFile => "లోకల్ ఫైళ్లను బ్రౌజ్ చేయండి";
  @override String get upload => "అప్‌లోడ్";
  @override String get remove => "తొలగించండి";
  @override String get replace => "మార్చండి";
  @override String get validateImage => "OCT స్కాన్‌ను ధృవీకరిస్తోంది...";
  @override String get startAnalysis => "AI రెటీనా పొరల విభజన ప్రారంభించండి";
  @override String get acquisitionParameters => "1. రోగి & స్కాన్ పారామితులు";
  @override String get eyeLaterality => "కంటి పార్శ్వం";
  @override String get rightEye => "OD (కుడి కన్ను)";
  @override String get leftEye => "OS (ఎడమ కన్ను)";
  @override String get acquisitionDevice => "OCT పరికరం";
  @override String get axialCalibration => "యాక్సియల్ కాలిబ్రేషన్ (μm / px)";
  @override String get dropzonePrompt => "రెటినల్ OCT B-స్కాన్ ఫైల్‌ను ఎంచుకోండి లేదా లాగండి";
  @override String get supportedFormats => "మద్దతు గల ఫార్మాట్లు: PNG, JPG, JPEG, TIFF (గరిష్టంగా 25MB)";
  @override String get sampleScans => "లేదా క్లినికల్ శాంపిల్ స్కాన్‌ను లోడ్ చేయండి:";
  @override String get validOCTDetected => "చెల్లుబాటు అయ్యే రెటినల్ OCT B-స్కాన్";
  @override String get invalidOCTDetected => "చెల్లని చిత్రం కనుగొనబడింది (నాన్-OCT)";
  @override String get startSegmentationBtn => "మెరుగైన ప్రీప్రాసెసింగ్ & U-Net విభజన ప్రారంభించండి";
  @override String get analysis => "AI విశ్లేషణ";
  @override String get preprocessing => "ప్రీప్రాసెసింగ్";
  @override String get enhancedPreprocessing => "మెరుగైన ప్రీప్రాసెసింగ్ (CLAHE)";
  @override String get segmentation => "U-Net బహుళ-పొరల విభజన";
  @override String get unetModel => "U-Net 4-డెప్త్ రెసిడ్యువల్ మోడల్";
  @override String get processing => "OCT స్కాన్ ప్రాసెస్ అవుతోంది...";
  @override String get completed => "పూర్తయింది";
  @override String get failed => "విశ్లేషణ విఫలమైంది";
  @override String get retry => "మళ్లీ ప్రయత్నించండి";
  @override String get step1Upload => "1. OCT చిత్రం అప్‌లోడ్ & నిల్వ";
  @override String get step2Validation => "2. కణజాల నిర్మాణం ధృవీకరణ";
  @override String get step3CLAHE => "3. బైలేటరల్ ఫిల్టర్ & CLAHE మెరుగుదల";
  @override String get step4UNet => "4. U-Net బహుళ-పొరల విభజన";
  @override String get step5Thickness => "5. పరిమాణాత్మక మందం గణన";
  @override String get step6Workspace => "6. బహుళ-పొర వర్క్‌స్పేస్ రెండరింగ్";
  @override String get original => "అసలు చిత్రం";
  @override String get preprocessed => "ప్రీప్రాసెస్డ్ (CLAHE)";
  @override String get segmentationMask => "సెగ్మెంటేషన్ మాస్క్";
  @override String get overlay => "ఓవర్‌లే";
  @override String get zoom => "జూమ్";
  @override String get reset => "రీసెట్ జూమ్";
  @override String get fullScreen => "స్క్రీన్‌కు అమర్చండి";
  @override String get layerVisibility => "రెటీనా పొరల దృశ్యమానత";
  @override String get showAll => "అన్నీ చూపించు";
  @override String get hideAll => "అన్నీ దాచు";
  @override String get overlayOpacity => "ఓవర్‌లే అపారదర్శకత";
  @override String get aiConfidence => "AI విశ్వసనీయత";
  @override String get imageQuality => "చిత్ర నాణ్యత";
  @override String get executionTime => "ఎగ్జిక్యూషన్ సమయం";
  @override String get calibrated => "కాలిబ్రేట్ చేయబడింది";
  @override String get uncalibrated => "భౌతిక కొలత అందుబాటులో లేదు — అమరిక డేటా అవసరం.";
  @override String get layerILM => "ILM (లోపలి పరిమిత పొర)";
  @override String get layerRNFL => "RNFL (రెటీనా నరాల ఫైబర్ పొర)";
  @override String get layerGCL => "GCL (గాంగ్లియన్ కణాల పొర)";
  @override String get layerIPL => "IPL (లోపలి ప్లెక్సిఫాం పొర)";
  @override String get layerINL => "INL (లోపలి కేంద్రక పొర)";
  @override String get layerOPL => "OPL (బాహ్య ప్లెక్సిఫాం పొర)";
  @override String get layerONL => "ONL (బాహ్య కేంద్రక పొర)";
  @override String get layerRPE => "RPE (రెటీనా పిగ్మెంట్ ఎపిథీలియం)";
  @override String get layer => "రెటీనా పొర";
  @override String get mean => "సగటు";
  @override String get min => "కనిష్ట";
  @override String get max => "గరిష్ట";
  @override String get area => "విస్తీర్ణం (px²)";
  @override String get layerThicknessMetrics => "పొరల మందం కొలమానాలు";
  @override String get reports => "నివేదికలు";
  @override String get generateReport => "PDF నివేదికను రూపొందించండి";
  @override String get preview => "ప్రివ్యూ నివేదిక";
  @override String get download => "PDF డౌన్‌లోడ్";
  @override String get share => "షేర్ చేయండి";
  @override String get reportGenerated => "డిజిటల్ క్లినికల్ నివేదికలు";
  @override String get printReport => "ప్రింట్";
  @override String get clinicalFindings => "ఆటోమేటెడ్ క్లినికల్ ఫలితాలు";
  @override String get specialistAttestation => "నిపుణుల సమీక్ష & ధృవీకరణ";
  @override String get disclaimerNote => "AI సహాయం మాత్రమే — ఫలితాలు పరిశోధన మరియు నిర్ణయ మద్దతు కోసం ఉద్దేశించబడ్డాయి.";
  @override String get settings => "సెట్టింగ్‌లు";
  @override String get profile => "క్లినికల్ ప్రొఫైల్";
  @override String get appearance => "రూపురేఖలు";
  @override String get language => "భాష";
  @override String get theme => "థీమ్ మోడ్";
  @override String get lightTheme => "లైట్";
  @override String get darkTheme => "డార్క్";
  @override String get systemTheme => "సిస్టమ్ డిఫాల్ట్";
  @override String get notifications => "నోటిఫికేషన్లు";
  @override String get privacy => "గోప్యత & భద్రత";
  @override String get about => "సిస్టమ్ గురించి";
  @override String get appVersion => "యాప్ వెర్షన్";
  @override String get regulatoryDisclaimer => "రెగ్యులేటరీ & డయాగ్నస్టిక్ నిరాకరణ";
  @override String get validOCTRequired => "దయచేసి సరైన రెటినల్ OCT చిత్రాన్ని అప్‌లోడ్ చేయండి.";
  @override String get patientRequired => "దయచేసి ముందుగా రోగి రికార్డును ఎంచుకోండి.";
  @override String get uploadSuccess => "అప్‌లోడ్ విజయవంతమైంది";
  @override String get analysisSuccess => "రెటీనా పొరల విభజన విజయవంతంగా పూర్తయింది.";
  @override String get reportGeneratedSuccess => "క్లినికల్ PDF నివేదిక విజయవంతంగా రూపొందించబడింది.";
  @override String get patientCreatedSuccess => "రోగి రికార్డు విజయవంతంగా నమోదు చేయబడింది.";
  @override String get sessionExpired => "సెషన్ ముగిసింది. దయచేసి మళ్లీ సైన్ ఇన్ చేయండి.";
  @override String get confirmDeletePatient => "మీరు ఖచ్చితంగా ఈ రోగి రికార్డును తొలగించాలనుకుంటున్నారా?";
}

// HINDI IMPLEMENTATION
class _AppLocalizationsHi extends AppLocalizations {
  _AppLocalizationsHi() : super('hi');
  @override String get appName => "RetinaSeg AI";
  @override String get appSubtitle => "OCT छवियों में स्वचालित रेटिना परत विभाजन";
  @override String get clinicalSuite => "नेत्र इमेजिंग प्लेटफॉर्म";
  @override String get login => "लॉग इन";
  @override String get register => "रजिस्टर";
  @override String get email => "ईमेल पता";
  @override String get password => "पासवर्ड";
  @override String get confirmPassword => "पासवर्ड की पुष्टि करें";
  @override String get forgotPassword => "पासवर्ड भूल गए?";
  @override String get signIn => "साइन इन";
  @override String get signUp => "साइन अप";
  @override String get logout => "लॉग आउट";
  @override String get fullName => "पूरा नाम और पद";
  @override String get role => "नैदानिक भूमिका";
  @override String get doctorDemo => "डॉक्टर खाता";
  @override String get adminDemo => "व्यवस्थापक खाता";
  @override String get ophthalmologistRole => "नेत्र रोग विशेषज्ञ";
  @override String get technicianRole => "नेत्र तकनीशियन";
  @override String get adminRole => "सिस्टम व्यवस्थापक";
  @override String get dashboard => "डैशबोर्ड";
  @override String get totalPatients => "कुल मरीज";
  @override String get totalOCTScans => "कुल OCT स्कैन";
  @override String get analysesCompleted => "पूर्ण किए गए विश्लेषण";
  @override String get analysesPending => "लंबित विश्लेषण";
  @override String get reportsGenerated => "PDF रिपोर्ट जेनरेटेड";
  @override String get recentAnalyses => "हालिया रेटिनल OCT विश्लेषण";
  @override String get quickActions => "त्वरित कार्य";
  @override String get welcomeText => "स्वागत है";
  @override String get activeSession => "सक्रिय नैदानिक सत्र";
  @override String get newScan => "नया स्कैन";
  @override String get viewAllHistory => "पूरा इतिहास देखें";
  @override String get patients => "मरीज";
  @override String get addPatient => "मरीज पंजीकृत करें";
  @override String get patientDetails => "मरीज का विवरण";
  @override String get patientId => "मरीज आईडी / MRN";
  @override String get name => "पूरा नाम";
  @override String get age => "उम्र";
  @override String get gender => "लिंग";
  @override String get contact => "संपर्क फोन";
  @override String get dateRegistered => "पंजीकरण तिथि";
  @override String get scanHistory => "स्कैन इतिहास";
  @override String get allGenders => "सभी लिंग";
  @override String get female => "महिला";
  @override String get male => "पुरुष";
  @override String get other => "अन्य";
  @override String get eyeCondition => "आंख की स्थिति / नैदानिक संकेत";
  @override String get medicalHistory => "चिकित्सा इतिहास";
  @override String get savePatientRecord => "मरीज रिकॉर्ड सहेजें";
  @override String get uploadOCT => "OCT अपलोड";
  @override String get selectImage => "रेटिनल OCT B-स्कैन फ़ाइल चुनें";
  @override String get chooseFile => "स्थानीय फ़ाइलें ब्राउज़ करें";
  @override String get upload => "अपलोड";
  @override String get remove => "हटाएं";
  @override String get replace => "बदलें";
  @override String get validateImage => "OCT स्कैन मान्य किया जा रहा है...";
  @override String get startAnalysis => "AI रेटिना परत विभाजन शुरू करें";
  @override String get acquisitionParameters => "1. मरीज और स्कैन पैरामीटर";
  @override String get eyeLaterality => "नेत्र पक्ष";
  @override String get rightEye => "OD (दाहिनी आंख)";
  @override String get leftEye => "OS (बाईं आंख)";
  @override String get acquisitionDevice => "OCT अधिग्रहण उपकरण";
  @override String get axialCalibration => "अक्षीय अंशांकन (μm / px)";
  @override String get dropzonePrompt => "रेटिनल OCT B-स्कैन फ़ाइल चुनें या खींचें";
  @override String get supportedFormats => "समर्थित प्रारूप: PNG, JPG, JPEG, TIFF (अधिकतम 25MB)";
  @override String get sampleScans => "या नैदानिक नमूना स्कैन लोड करें:";
  @override String get validOCTDetected => "मान्य रेटिनल OCT B-स्कैन";
  @override String get invalidOCTDetected => "अमान्य छवि पहचानी गई (गैर-OCT)";
  @override String get startSegmentationBtn => "उन्नत प्रीप्रोसेसिंग और U-Net विभाजन शुरू करें";
  @override String get analysis => "AI विश्लेषण";
  @override String get preprocessing => "प्रीप्रोसेसिंग";
  @override String get enhancedPreprocessing => "उन्नत प्रीप्रोसेसिंग (CLAHE)";
  @override String get segmentation => "U-Net बहु-परत विभाजन";
  @override String get unetModel => "U-Net 4-गहराई अवशिष्ट मॉडल";
  @override String get processing => "OCT स्कैन संसाधित हो रहा है...";
  @override String get completed => "पूरा हुआ";
  @override String get failed => "विश्लेषण विफल रहा";
  @override String get retry => "पुनः प्रयास करें";
  @override String get step1Upload => "1. OCT छवि अपलोड और भंडारण";
  @override String get step2Validation => "2. ऊतक संरचना सत्यापन";
  @override String get step3CLAHE => "3. द्विपक्षीय फ़िल्टर और CLAHE सुधार";
  @override String get step4UNet => "4. U-Net बहु-परत विभाजन";
  @override String get step5Thickness => "5. मात्रात्मक मोटाई गणना";
  @override String get step6Workspace => "6. बहु-परत कार्यक्षेत्र प्रतिपादन";
  @override String get original => "मूल छवि";
  @override String get preprocessed => "प्रीप्रोसेस्ड (CLAHE)";
  @override String get segmentationMask => "विभाजन मास्क";
  @override String get overlay => "ओवरले";
  @override String get zoom => "ज़ूम";
  @override String get reset => "ज़ूम रीसेट";
  @override String get fullScreen => "स्क्रीन में फिट करें";
  @override String get layerVisibility => "रेटिना परत दृश्यता";
  @override String get showAll => "सभी दिखाएं";
  @override String get hideAll => "सभी छिपाएं";
  @override String get overlayOpacity => "ओवरले अपारदर्शिता";
  @override String get aiConfidence => "AI विश्वास स्तर";
  @override String get imageQuality => "छवि गुणवत्ता";
  @override String get executionTime => "निष्पादन समय";
  @override String get calibrated => "कैलिब्रेटेड";
  @override String get uncalibrated => "भौतिक माप अनुपलब्ध — अंशांकन डेटा आवश्यक।";
  @override String get layerILM => "ILM (आंतरिक सीमित झिल्ली)";
  @override String get layerRNFL => "RNFL (रेटिनल तंत्रिका फाइबर परत)";
  @override String get layerGCL => "GCL (गैंग्लियन कोशिका परत)";
  @override String get layerIPL => "IPL (आंतरिक प्लेक्सीफॉर्म परत)";
  @override String get layerINL => "INL (आंतरिक परमाणु परत)";
  @override String get layerOPL => "OPL (बाहरी प्लेक्सीफॉर्म परत)";
  @override String get layerONL => "ONL (बाहरी परमाणु परत)";
  @override String get layerRPE => "RPE (रेटिनल पिगमेंट एपिथीलियम)";
  @override String get layer => "रेटिना परत";
  @override String get mean => "औसत";
  @override String get min => "न्यूनतम";
  @override String get max => "अधिकतम";
  @override String get area => "क्षेत्रफल (px²)";
  @override String get layerThicknessMetrics => "परत मोटाई मेट्रिक्स";
  @override String get reports => "रिपोर्ट्स";
  @override String get generateReport => "PDF रिपोर्ट जेनरेट करें";
  @override String get preview => "रिपोर्ट पूर्वावलोकन";
  @override String get download => "PDF डाउनलोड";
  @override String get share => "साझा करें";
  @override String get reportGenerated => "डिजिटल नैदानिक रिपोर्ट";
  @override String get printReport => "प्रिंट";
  @override String get clinicalFindings => "स्वचालित नैदानिक निष्कर्ष";
  @override String get specialistAttestation => "विशेषज्ञ समीक्षा और सत्यापन";
  @override String get disclaimerNote => "केवल AI सहायता — परिणाम अनुसंधान और निर्णय समर्थन के लिए हैं।";
  @override String get settings => "सेटिंग्स";
  @override String get profile => "नैदानिक प्रोफाइल";
  @override String get appearance => "दिखावट";
  @override String get language => "भाषा";
  @override String get theme => "थीम मोड";
  @override String get lightTheme => "लाइट";
  @override String get darkTheme => "डार्क";
  @override String get systemTheme => "सिस्टम डिफ़ॉल्ट";
  @override String get notifications => "सूचनाएं";
  @override String get privacy => "गोपनीयता और सुरक्षा";
  @override String get about => "सिस्टम के बारे में";
  @override String get appVersion => "ऐप संस्करण";
  @override String get regulatoryDisclaimer => "नियामक और नैदानिक अस्वीकरण";
  @override String get validOCTRequired => "कृपया एक मान्य रेटिनल OCT छवि अपलोड करें।";
  @override String get patientRequired => "कृपया पहले एक मरीज रिकॉर्ड चुनें।";
  @override String get uploadSuccess => "अपलोड सफल रहा";
  @override String get analysisSuccess => "रेटिना परत विभाजन सफलतापूर्वक पूरा हुआ।";
  @override String get reportGeneratedSuccess => "नैदानिक PDF रिपोर्ट सफलतापूर्वक बनाई गई।";
  @override String get patientCreatedSuccess => "मरीज रिकॉर्ड सफलतापूर्वक पंजीकृत किया गया।";
  @override String get sessionExpired => "सत्र समाप्त हो गया। कृपया पुन: साइन इन करें।";
  @override String get confirmDeletePatient => "क्या आप वाकई इस मरीज रिकॉर्ड को हटाना चाहते हैं?";
}

// TAMIL IMPLEMENTATION
class _AppLocalizationsTa extends AppLocalizations {
  _AppLocalizationsTa() : super('ta');
  @override String get appName => "RetinaSeg AI";
  @override String get appSubtitle => "OCT படங்களில் தானியங்கி விழித்திரை அடுக்கு பிரிப்பு";
  @override String get clinicalSuite => "கண் மருத்துவ இமேஜிங் தளம்";
  @override String get login => "உள்நுழைவு";
  @override String get register => "பதிவு செய்";
  @override String get email => "மின்னஞ்சல் முகவரி";
  @override String get password => "கடவுச்சொல்";
  @override String get confirmPassword => "கடவுச்சொல்லை உறுதிப்படுத்தவும்";
  @override String get forgotPassword => "கடவுச்சொல் மறந்துவிட்டதா?";
  @override String get signIn => "உள்நுழைய";
  @override String get signUp => "பதிவு செய்க";
  @override String get logout => "வெளியேறு";
  @override String get fullName => "முழு பெயர் & பதவி";
  @override String get role => "மருத்துவப் பணி";
  @override String get doctorDemo => "மருத்துவர் கணக்கு";
  @override String get adminDemo => "நிர்வாகி கணக்கு";
  @override String get ophthalmologistRole => "கண் மருத்துவர்";
  @override String get technicianRole => "கண் மருத்துவ தொழில்நுட்ப வல்லுநர்";
  @override String get adminRole => "கணினி நிர்வாகி";
  @override String get dashboard => "டாஷ்போர்டு";
  @override String get totalPatients => "மொத்த நோயாளிகள்";
  @override String get totalOCTScans => "மொத்த OCT ஸ்கேன்கள்";
  @override String get analysesCompleted => "முடிக்கப்பட்ட பகுப்பாய்வுகள்";
  @override String get analysesPending => "நிலுவையில் உள்ள பகுப்பாய்வுகள்";
  @override String get reportsGenerated => "PDF அறிக்கைகள்";
  @override String get recentAnalyses => "சமீபத்திய விழித்திரை OCT பகுப்பாய்வுகள்";
  @override String get quickActions => "விரைவு நடவடிக்கைகள்";
  @override String get welcomeText => "வரவேற்கிறோம்";
  @override String get activeSession => "செயலில் உள்ள மருத்துவ அமர்வு";
  @override String get newScan => "புதிய ஸ்கேன்";
  @override String get viewAllHistory => "முழு வரலாற்றையும் காண்க";
  @override String get patients => "நோயாளிகள்";
  @override String get addPatient => "நோயாளியைப் பதிவு செய்க";
  @override String get patientDetails => "நோயாளி விவரங்கள்";
  @override String get patientId => "நோயாளி ID / MRN";
  @override String get name => "முழு பெயர்";
  @override String get age => "வயது";
  @override String get gender => "பாலினம்";
  @override String get contact => "தொலைபேசி எண்";
  @override String get dateRegistered => "பதிவு செய்த தேதி";
  @override String get scanHistory => "ஸ்கேன் வரலாறு";
  @override String get allGenders => "அனைத்து பாலினங்களும்";
  @override String get female => "பெண்";
  @override String get male => "ஆண்";
  @override String get other => "மற்றவை";
  @override String get eyeCondition => "கண் நிலை / மருத்துவ அறிகுறி";
  @override String get medicalHistory => "மருத்துவ வரலாறு";
  @override String get savePatientRecord => "நோயாளி பதிவைச் சேமிக்கவும்";
  @override String get uploadOCT => "OCT பதிவேற்றம்";
  @override String get selectImage => "விழித்திரை OCT B-ஸ்கேன் கோப்பைத் தேர்ந்தெடுக்கவும்";
  @override String get chooseFile => "உள்ளூர் கோப்புகளை உலாவவும்";
  @override String get upload => "பதிவேற்று";
  @override String get remove => "நீக்கு";
  @override String get replace => "மாற்று";
  @override String get validateImage => "OCT ஸ்கேன் சரிபார்க்கப்படுகிறது...";
  @override String get startAnalysis => "AI விழித்திரை அடுக்கு பிரிப்பைத் தொடங்கு";
  @override String get acquisitionParameters => "1. நோயாளி & ஸ்கேன் அளவுருக்கள்";
  @override String get eyeLaterality => "கண் பக்கவாட்டு";
  @override String get rightEye => "OD (வலது கண்)";
  @override String get leftEye => "OS (இடது கண்)";
  @override String get acquisitionDevice => "OCT சாதனம்";
  @override String get axialCalibration => "அச்சு அளவுத்திருத்தம் (μm / px)";
  @override String get dropzonePrompt => "விழித்திரை OCT B-ஸ்கேன் கோப்பைத் தேர்ந்தெடுக்கவும் அல்லது இழுக்கவும்";
  @override String get supportedFormats => "ஆதரிக்கப்படும் வடிவங்கள்: PNG, JPG, JPEG, TIFF (அதிகபட்சம் 25MB)";
  @override String get sampleScans => "அல்லது மருத்துவ மாதிரி ஸ்கேனை ஏற்றவும்:";
  @override String get validOCTDetected => "செல்லுபடியாகும் விழித்திரை OCT B-ஸ்கேன்";
  @override String get invalidOCTDetected => "தவறான படம் கண்டறியப்பட்டது (OCT அல்லாதது)";
  @override String get startSegmentationBtn => "மேம்படுத்தப்பட்ட முன்செயலாக்கம் & U-Net பிரிப்பைத் தொடங்கு";
  @override String get analysis => "AI பகுப்பாய்வு";
  @override String get preprocessing => "முன்செயலாக்கம்";
  @override String get enhancedPreprocessing => "மேம்பட்ட முன்செயலாக்கம் (CLAHE)";
  @override String get segmentation => "U-Net பல அடுக்கு பிரிப்பு";
  @override String get unetModel => "U-Net 4-ஆழ மாதிரி";
  @override String get processing => "OCT ஸ்கேன் செயலாக்கப்படுகிறது...";
  @override String get completed => "முடிந்தது";
  @override String get failed => "பகுப்பாய்வு தோல்வியடைந்தது";
  @override String get retry => "மீண்டும் முயற்சி செய்";
  @override String get step1Upload => "1. OCT படப் பதிவேற்றம் & சேமிப்பு";
  @override String get step2Validation => "2. திசு அமைப்பு சரிபார்ப்பு";
  @override String get step3CLAHE => "3. இருதரப்பு வடிகட்டி & CLAHE மேம்பாடு";
  @override String get step4UNet => "4. U-Net பல அடுக்கு பிரிப்பு";
  @override String get step5Thickness => "5. தடிமன் கணக்கீடு";
  @override String get step6Workspace => "6. பல அடுக்கு காட்சிப்படுத்தல்";
  @override String get original => "அசல் படம்";
  @override String get preprocessed => "முன்செயலாக்கப்பட்டது (CLAHE)";
  @override String get segmentationMask => "பிரிப்பு மாஸ்க்";
  @override String get overlay => "மேலடுக்கு";
  @override String get zoom => "பெரிதாக்கு";
  @override String get reset => "மீட்டமை";
  @override String get fullScreen => "முழு திரை";
  @override String get layerVisibility => "விழித்திரை அடுக்கு பார்வை";
  @override String get showAll => "அனைத்தையும் காட்டு";
  @override String get hideAll => "அனைத்தையும் மறை";
  @override String get overlayOpacity => "மேலடுக்கு ஒளிபுகாநிலை";
  @override String get aiConfidence => "AI நம்பிக்கை நிலை";
  @override String get imageQuality => "படத் தரம்";
  @override String get executionTime => "செயலாக்க நேரம்";
  @override String get calibrated => "அளவீடு செய்யப்பட்டது";
  @override String get uncalibrated => "உடல் அளவீடு கிடைக்கவில்லை — அளவுத்திருத்தத் தரவு தேவை.";
  @override String get layerILM => "ILM (உள் வரம்பு சவ்வு)";
  @override String get layerRNFL => "RNFL (விழித்திரை நரம்பு இழை அடுக்கு)";
  @override String get layerGCL => "GCL (கேங்க்லியன் செல் அடுக்கு)";
  @override String get layerIPL => "IPL (உள் பிளெக்சிஃபார்ம் அடுக்கு)";
  @override String get layerINL => "INL (உள் அணுக்கரு அடுக்கு)";
  @override String get layerOPL => "OPL (வெளி பிளெக்சிஃபார்ம் அடுக்கு)";
  @override String get layerONL => "ONL (வெளி அணுக்கரு அடுக்கு)";
  @override String get layerRPE => "RPE (விழித்திரை நிறமி எபிட்டிலியம்)";
  @override String get layer => "விழித்திரை அடுக்கு";
  @override String get mean => "சராசரி";
  @override String get min => "குறைந்தபட்சம்";
  @override String get max => "அதிகபட்சம்";
  @override String get area => "பரப்பளவு (px²)";
  @override String get layerThicknessMetrics => "அடுக்கு தடிமன் அளவீடுகள்";
  @override String get reports => "அறிக்கைகள்";
  @override String get generateReport => "PDF அறிக்கையை உருவாக்கு";
  @override String get preview => "முன்னோட்டம்";
  @override String get download => "PDF பதிவிறக்கு";
  @override String get share => "பகிர்";
  @override String get reportGenerated => "டிஜிட்டல் மருத்துவ அறிக்கைகள்";
  @override String get printReport => "அச்சிடு";
  @override String get clinicalFindings => "தானியங்கி மருத்துவக் கண்டுபிடிப்புகள்";
  @override String get specialistAttestation => "நிபுணர் மதிப்பாய்வு & சான்றொப்பம்";
  @override String get disclaimerNote => "AI உதவி மட்டுமே — முடிவுகள் ஆராய்ச்சி மற்றும் முடிவு ஆதரவுக்கானவை.";
  @override String get settings => "அமைப்புகள்";
  @override String get profile => "மருத்துவ சுயவிவரம்";
  @override String get appearance => "தோற்றம்";
  @override String get language => "மொழி";
  @override String get theme => "தீம் முறை";
  @override String get lightTheme => "வெளிச்சம்";
  @override String get darkTheme => "இருள்";
  @override String get systemTheme => "கணினி இயல்புநிலை";
  @override String get notifications => "அறிவிப்புகள்";
  @override String get privacy => "தனியுரிமை & பாதுகாப்பு";
  @override String get about => "அமைப்பு பற்றி";
  @override String get appVersion => "பயன்பாட்டு பதிப்பு";
  @override String get regulatoryDisclaimer => "ஒழுங்குமுறை & மருத்துவ மறுப்பு";
  @override String get validOCTRequired => "சரியான விழித்திரை OCT படத்தைப் பதிவேற்றவும்.";
  @override String get patientRequired => "முதலில் ஒரு நோயாளி பதிவைத் தேர்ந்தெடுக்கவும்.";
  @override String get uploadSuccess => "பதிவேற்றம் வெற்றிகரமாக முடிந்தது";
  @override String get analysisSuccess => "விழித்திரை அடுக்கு பிரிப்பு வெற்றிகரமாக முடிந்தது.";
  @override String get reportGeneratedSuccess => "மருத்துவ PDF அறிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது.";
  @override String get patientCreatedSuccess => "நோயாளி பதிவு வெற்றிகரமாக பதிவு செய்யப்பட்டது.";
  @override String get sessionExpired => "அமர்வு காலாவதியானது. மீண்டும் உள்நுழையவும்.";
  @override String get confirmDeletePatient => "இந்த நோயாளி பதிவை நிச்சயமாக நீக்க விரும்புகிறீர்களா?";
}
